USE nutrisci;

-- Load Food Names
LOAD DATA LOCAL INFILE 'sql/FOOD NAME.csv' 
INTO TABLE cnf_food_name
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load Nutrient Amounts
LOAD DATA LOCAL INFILE 'sql/NUTRIENT AMOUNT.csv'
INTO TABLE cnf_nutrient_amount
FIELDS TERMINATED BY ','
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load Food Groups
LOAD DATA LOCAL INFILE 'sql/FOOD GROUP.csv'
INTO TABLE cnf_food_group
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

-- Load Nutrient Names
LOAD DATA LOCAL INFILE 'sql/NUTRIENT NAME.csv'
INTO TABLE cnf_nutrient_name
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;